# Generated by Django 3.2.4 on 2021-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBankingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnn',
            name='crName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='txnn',
            name='drName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
