# Generated by Django 3.2.4 on 2021-07-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBankingSystem', '0002_auto_20210718_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='txnn',
            old_name='crName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='txnn',
            name='drName',
        ),
    ]
