# Generated by Django 3.2.4 on 2021-07-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBankingSystem', '0003_auto_20210718_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txnn',
            name='name',
        ),
    ]
