# Generated by Django 3.2.4 on 2021-07-19 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBankingSystem', '0004_remove_txnn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='txnn',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
