# Generated by Django 3.2.4 on 2021-07-19 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBankingSystem', '0005_txnn_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txnn',
            name='date',
        ),
        migrations.RemoveField(
            model_name='txnn',
            name='time',
        ),
        migrations.AddField(
            model_name='txnn',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
