# Generated by Django 3.2.4 on 2021-07-19 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleBankingSystem', '0006_auto_20210719_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txnn',
            name='date_time',
        ),
        migrations.AddField(
            model_name='txnn',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txnn',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
